version: '3.4'

services:
  schemaacrossdbviewsamle:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=44345
      - ConnectionStrings__sampledb=Server=db;Port=3306;Uid=username;Pwd=secret;Database=appdb
    ports:
      - "8758:80"
      - "44345:443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro