version: '3.4'

services:
  schemaacrossdbviewsamle:
    image: ${DOCKER_REGISTRY-}schemaacrossdbviewsamle
    build:
      context: .
      dockerfile: SchemaAcrossDbViewSamle/Dockerfile
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: appdb
      MYSQL_USER: username
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: password
      TZ: "Asia/Tokyo"
    ports:
      - "3306:3306"
    volumes:
      - data-volume:/var/lib/mysql
      - ./dockerscripts/db/sql:/docker-entrypoint-initdb.d
volumes:
  data-volume:
    driver: local
