// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchemaAcrossDbViewSamle.Data;

namespace SchemaAcrossDbViewSamle.Migrations
{
    [DbContext(typeof(SampleDbContext))]
    [Migration("20190318043147_addview")]
    partial class addview
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SchemaAcrossDbViewSamle.Data.Entities.Test1", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<string>("QueryTest2Id");

                    b.HasKey("Id");

                    b.ToTable("Test1");

                    b.HasData(
                        new
                        {
                            Id = "test1-1",
                            Name = "test1",
                            QueryTest2Id = "test2-1"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
